### ISSUE TITLE
what are the plans for this?

### ISSUE THREAD

**Issue by fauno** [schmidlorenz/wp-imapauth#5]
i was just going to test this plugin :(

is it discontinued because you lost interest on imap auth or are you planning another plugin?

**Comment by schmidlorenz** [comment]
Hi and thanks for your interest!

I recently went through my GitHub projects and added a _discontinued_ stamp on the ones I am not using anymore and/or do not intend to develop further.
To be more specific, I indeed wrote a new plugin (the [External Authentication Plugin](https://github.com/schmidlorenz/wp-extauth)) which tackles many points I was unhappy with for the IMAP plugin. The new plugin blocks a user of changing any profile settings such as email address or password in the Wordpress database. Instead he/she is redirected to an external site where I have a common interface for all the services on my server (email, other services etc.). So now I control the user profiles in the Wordpress database externally (by changing the database directly) and do not rely on IMAP authentication anymore. This will become particularly interesting with the new Wordpress [REST API](https://developer.wordpress.com/docs/api/) in mind.

Nevertheless the IMAP plugin should still work more or less and I am happy to accept PRs if bugs appear. Does this answer your question?
